# Form implementation generated from reading ui file 'frm_voice.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(475, 218)
        self.btnClose = QtWidgets.QPushButton(Form)
        self.btnClose.setGeometry(QtCore.QRect(370, 170, 75, 23))
        self.btnClose.setObjectName("btnClose")
        self.lblText = QtWidgets.QLabel(Form)
        self.lblText.setGeometry(QtCore.QRect(20, 10, 341, 41))
        self.lblText.setStyleSheet("color: rgb(255, 85, 127);\n"
                                   "font: 75 10pt \"MS Shell Dlg 2\";")
        self.lblText.setObjectName("lblText")
        self.btnRead = QtWidgets.QPushButton(Form)
        self.btnRead.setGeometry(QtCore.QRect(20, 170, 321, 23))
        self.btnRead.setObjectName("btnRead")
        self.rbGerman = QtWidgets.QRadioButton(Form)
        self.rbGerman.setGeometry(QtCore.QRect(380, 60, 82, 17))
        self.rbGerman.setChecked(True)
        self.rbGerman.setObjectName("rbGerman")
        self.rbEnglish = QtWidgets.QRadioButton(Form)
        self.rbEnglish.setGeometry(QtCore.QRect(380, 80, 82, 17))
        self.rbEnglish.setObjectName("rbEnglish")
        self.txtText = QtWidgets.QTextEdit(Form)
        self.txtText.setGeometry(QtCore.QRect(20, 50, 321, 111))
        self.txtText.setObjectName("txtText")

        self.retranslateUi(Form)
        self.btnClose.clicked.connect(self.btnClose_click)
        self.btnRead.clicked.connect(self.btnRead_click)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Beispiel Sprachausgabe"))
        self.btnClose.setText(_translate("Form", "Beenden"))
        self.lblText.setText(_translate("Form", "Geben Sie den Text ein, welcher vorgelesen werden soll!"))
        self.btnRead.setText(_translate("Form", "Vorlesen"))
        self.rbGerman.setText(_translate("Form", "Deutsch"))
        self.rbEnglish.setText(_translate("Form", "Englisch"))

