# Form implementation generated from reading ui file 'bsp_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmLiegeplatzerfasssung(object):
    def setupUi(self, frmLiegeplatzerfasssung):
        frmLiegeplatzerfasssung.setObjectName("frmLiegeplatzerfasssung")
        frmLiegeplatzerfasssung.resize(552, 268)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/__Temp__/Bild1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        frmLiegeplatzerfasssung.setWindowIcon(icon)
        self.txtBezeichnung = QtWidgets.QLineEdit(frmLiegeplatzerfasssung)
        self.txtBezeichnung.setGeometry(QtCore.QRect(110, 50, 113, 20))
        self.txtBezeichnung.setStyleSheet("color: rgb(170, 85, 0);")
        self.txtBezeichnung.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txtBezeichnung.setObjectName("txtBezeichnung")
        self.lblBezeicnung = QtWidgets.QLabel(frmLiegeplatzerfasssung)
        self.lblBezeicnung.setGeometry(QtCore.QRect(30, 50, 71, 20))
        self.lblBezeicnung.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblBezeicnung.setObjectName("lblBezeicnung")
        self.txtLaenge = QtWidgets.QLineEdit(frmLiegeplatzerfasssung)
        self.txtLaenge.setGeometry(QtCore.QRect(110, 80, 113, 20))
        self.txtLaenge.setObjectName("txtLaenge")
        self.lblLaenge = QtWidgets.QLabel(frmLiegeplatzerfasssung)
        self.lblLaenge.setGeometry(QtCore.QRect(30, 80, 71, 20))
        self.lblLaenge.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblLaenge.setObjectName("lblLaenge")
        self.txtBreite = QtWidgets.QLineEdit(frmLiegeplatzerfasssung)
        self.txtBreite.setGeometry(QtCore.QRect(110, 110, 113, 20))
        self.txtBreite.setObjectName("txtBreite")
        self.lblBreite = QtWidgets.QLabel(frmLiegeplatzerfasssung)
        self.lblBreite.setGeometry(QtCore.QRect(30, 110, 71, 20))
        self.lblBreite.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblBreite.setObjectName("lblBreite")
        self.txtWassertiefe = QtWidgets.QLineEdit(frmLiegeplatzerfasssung)
        self.txtWassertiefe.setGeometry(QtCore.QRect(110, 140, 113, 20))
        self.txtWassertiefe.setObjectName("txtWassertiefe")
        self.lblWasserteife = QtWidgets.QLabel(frmLiegeplatzerfasssung)
        self.lblWasserteife.setGeometry(QtCore.QRect(0, 140, 101, 20))
        self.lblWasserteife.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblWasserteife.setObjectName("lblWasserteife")
        self.lblBild = QtWidgets.QLabel(frmLiegeplatzerfasssung)
        self.lblBild.setGeometry(QtCore.QRect(240, 50, 41, 20))
        self.lblBild.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblBild.setObjectName("lblBild")
        self.btnSave = QtWidgets.QPushButton(frmLiegeplatzerfasssung)
        self.btnSave.setGeometry(QtCore.QRect(110, 210, 121, 41))
        self.btnSave.setStyleSheet("")
        self.btnSave.setObjectName("btnSave")
        self.btnNew = QtWidgets.QPushButton(frmLiegeplatzerfasssung)
        self.btnNew.setGeometry(QtCore.QRect(245, 210, 121, 41))
        self.btnNew.setObjectName("btnNew")
        self.btnClose = QtWidgets.QPushButton(frmLiegeplatzerfasssung)
        self.btnClose.setGeometry(QtCore.QRect(380, 210, 121, 41))
        self.btnClose.setObjectName("btnClose")
        self.label = QtWidgets.QLabel(frmLiegeplatzerfasssung)
        self.label.setGeometry(QtCore.QRect(290, 50, 211, 141))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Bilder/Liegeplatz.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.cbStatus = QtWidgets.QComboBox(frmLiegeplatzerfasssung)
        self.cbStatus.setGeometry(QtCore.QRect(110, 170, 111, 22))
        self.cbStatus.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.cbStatus.setObjectName("cbStatus")
        self.cbStatus.addItem("")
        self.cbStatus.addItem("")
        self.cbStatus.addItem("")
        self.cbStatus.addItem("")
        self.lblStatus = QtWidgets.QLabel(frmLiegeplatzerfasssung)
        self.lblStatus.setGeometry(QtCore.QRect(0, 170, 101, 20))
        self.lblStatus.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblStatus.setObjectName("lblStatus")

        self.retranslateUi(frmLiegeplatzerfasssung)
        self.btnSave.clicked.connect(self.btnSave.click) # type: ignore
        self.btnNew.clicked.connect(self.btnNew.click) # type: ignore
        self.btnClose.clicked.connect(self.btnClose.click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(frmLiegeplatzerfasssung)

    def retranslateUi(self, frmLiegeplatzerfasssung):
        _translate = QtCore.QCoreApplication.translate
        frmLiegeplatzerfasssung.setWindowTitle(_translate("frmLiegeplatzerfasssung", "Liegeplatzdaten"))
        self.lblBezeicnung.setText(_translate("frmLiegeplatzerfasssung", "Bezeichnung:"))
        self.lblLaenge.setText(_translate("frmLiegeplatzerfasssung", "Länge (m):"))
        self.lblBreite.setText(_translate("frmLiegeplatzerfasssung", "Breite (m):"))
        self.lblWasserteife.setText(_translate("frmLiegeplatzerfasssung", "Wassertiefe (cm):"))
        self.lblBild.setText(_translate("frmLiegeplatzerfasssung", "Bild:"))
        self.btnSave.setText(_translate("frmLiegeplatzerfasssung", "Daten speichern"))
        self.btnNew.setText(_translate("frmLiegeplatzerfasssung", "Neues Bild"))
        self.btnClose.setText(_translate("frmLiegeplatzerfasssung", "Dialog schließen"))
        self.cbStatus.setItemText(0, _translate("frmLiegeplatzerfasssung", "verfügbar"))
        self.cbStatus.setItemText(1, _translate("frmLiegeplatzerfasssung", "vermietet"))
        self.cbStatus.setItemText(2, _translate("frmLiegeplatzerfasssung", "belegt"))
        self.cbStatus.setItemText(3, _translate("frmLiegeplatzerfasssung", "gesperrt"))
        self.lblStatus.setText(_translate("frmLiegeplatzerfasssung", "Status:"))
